boostcampwm-2022/web15-Teleparty

.prettierrc
frontend/package-lock.json
frontend/src/App.tsx
frontend/src/components/Palette/Palette.component.tsx
frontend/src/components/Palette/Palette.styles.tsx
frontend/src/global-styles/theme.ts
frontend/src/pages/Test.tsx

Closes #3 
- Prettier useTabs 설정 제거
- `package-lock.json` 추가
- 글로벌 색상 추가
- 색상 선택 컴포넌트 구현

[FEAT] 색상 선택 컴포넌트 구현

---

frontend/src/components/Thickness/Thickness.component.tsx
frontend/src/components/Thickness/Thickness.styles.tsx
frontend/src/global-styles/theme.ts
frontend/src/pages/Test.tsx

[FEAT] 굵기 선택 컴포넌트 구현

---

frontend/src/components/Canvas/Canvas.component.tsx
frontend/src/components/Canvas/utils/Line.ts
frontend/src/utils/debounce.ts

closes #16
- Line 내부의 데이터 구조를 선에서 점으로 변경
- 캔버스 렌더링에 프레임 디바운스 적용
- Line 클래스의 pushPoint 메서드에 중복 성분 제거 알고리즘 추가

[FEAT] 캔버스 성능 최적화

---

frontend/src/components/Transparency/Transparency.component.tsx
frontend/src/components/Transparency/Transparency.styles.tsx
frontend/src/global-styles/theme.ts
frontend/src/pages/Test.tsx

[FEAT] 투명도 조절 컴포넌트 구현

---

backend/package-lock.json
backend/package.json
backend/src/app.ts
backend/src/domains/canvas/canvas.ts
backend/src/types/canvasData.ts
backend/test/canvasSocket.test.ts
backend/test/test.ts

closes #6
- canvas 관련 소켓 이벤트 작성
- 테스트 코드 작성

[FEAT] 서버 소켓 이벤트 구현

---

frontend/src/components/Canvas/Canvas.component.tsx

closes #8 
- `Ctrl(Cmd) + z`를 입력하여 이전 그림판 상태로 되돌리기 구현

[FEAT] 그림판 되돌리기 구현

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Canvas/Canvas.component.tsx
frontend/src/components/Canvas/utils/Ellipse.ts
frontend/src/components/Canvas/utils/Polygon.ts
frontend/src/components/Canvas/utils/Rectangle.ts
frontend/src/components/Canvas/utils/StraightLine.ts
frontend/src/components/Canvas/utils/canvas.ts
frontend/src/components/Icon/Icon.tsx
frontend/src/components/ToolBox/ToolBox.component.tsx
frontend/src/components/ToolBox/ToolBox.styles.tsx
frontend/src/store/tool.ts

closes #9
- ToolBox 컴포넌트 UI 구현
- 도구 선택을 위한 상태관리 구현
- 지우개 구현
- 도형(직사각형, 원) 그리기 도구 구현
- 직선 그리기 도구 구현
- 닫힌 도형 채우기 도구 구현

[FEAT] 캔버스 도구(지우개, 도형, 닫힌 도형 채우기) 구현

---

backend/src/app.ts
backend/src/domains/canvas/canvas.ts
backend/src/types/canvasData.ts
backend/test/canvasSocket.test.ts

closes #26
- 변수명을 적절하게 변경
- 린트 경고 수정
- api 문서와 다른부분 수정

[REFACTOR] 백엔드 리팩토링 및 버그수정

---

package-lock.json
packages/shared/.eslintrc.json
packages/shared/.gitignore
packages/shared/package.json
packages/shared/tsconfig.json

closes #57 
- 린트 설정및 관련 의존성 추가
- tsconfig.json
- .gitignore 추가

[CHORE] shared 패키지 세팅

---

packages/frontend/src/components/MoonTimer/MoonTimer.component.tsx
packages/frontend/src/components/MoonTimer/MoonTimer.styles.tsx

closes #41
- 달 모양 타이머 컴포넌트를 구현했습니다.

[FEAT] MoonTimer 컴포넌트 구현

---

packages/frontend/package.json
packages/frontend/src/App.tsx
packages/frontend/src/components/common/Button.tsx
packages/frontend/src/global-styles/global-styles.ts
packages/frontend/src/global-styles/styled.d.ts
packages/frontend/src/global-styles/theme.ts
packages/frontend/src/pages/LandingPage/LandingPage.component.tsx
packages/frontend/src/pages/RoomPage/RoomPage.component.tsx
packages/frontend/src/store/roomId.ts
packages/frontend/src/store/socket.ts

closes #30
- 플레이어 초대 링크 생성 기능 구현
- 방 페이지에서 새로고침, 뒤로가기 시 경고창 생성
- 방 페이지로 비정상적인 접근 시 랜딩페이지로 이동

[FEAT] 초대링크 생성

---

package-lock.json
packages/frontend/package.json
packages/frontend/src/hooks/useCatchMind.tsx
packages/frontend/src/types/game.ts

closes #74
- 비즈니스 로직 분리를 위한 useCatchMind 커스텀 훅 구현

[FEAT] useCatchMind 커스텀 훅 구현

---

packages/frontend/src/components/GameModeSegmentedControl/GameModeSegmentedControl.component.tsx
packages/frontend/src/components/GameModeSegmentedControl/GameModeSegmentedControl.styles.tsx
packages/frontend/src/constants/game-mode.tsx

- GameModeSegmentedControl
closes #34

[FEAT] 게임 모드 선택 컴포넌트 구현

---

packages/backend/src/app.ts

[fix] player, room 도메인 소켓 연결

---

packages/backend/src/domains/chat/inbound/chatIn.controller.ts
packages/backend/src/domains/player/inbound/player.controller.ts
packages/backend/src/domains/room/entity/room.service.ts
packages/backend/src/domains/room/outbound/room.event.adapter.ts
packages/backend/src/domains/room/outbound/room.port.ts

#45
- chatting 중복 이벤트 제거
- disconnect 이벤트 적용

[FEAT] disconnect 이벤트 구현

---

.github/workflows/CD.yml
packages/frontend/src/pages/LandingPage/LandingPage.component.tsx

closes #83 
- CD 액션 발생 조건 변경 -> main 브랜치의 pr이 닫혔을 때 작동
- CD 워크플로우 변경
-  cd 시 npm install, test, build 실행 X -> 이미 dev에서 하고 왔기 때문에
- NCP 인스턴스에서 명령어 변경 -> NGINX에서 정적파일을 제공하는 걸로 변경하였기에 build만 함

[FIX] CD 에러 수정

---

.github/workflows/slackAlram.yml

closes #103 
- 19시에 pr개수와 제목이 슬랙 알람으로 감

feat: 슬랙 7시 알람

---

package-lock.json
packages/frontend/.eslintrc.json
packages/frontend/package.json
packages/frontend/src/pages/RoomPage/RoomPage.component.tsx

closes #109 
- eslint-config-react-app, eslint-plugin-react-hooks 설치 및 설정
- 새로 적용된 lint에 대한 오류 수정
- 조건부 hook 호출 삭제
- RoomPage 컴포넌트 useEffect 종속성 추가

[CHORE] 프론트엔드 eslint 플러그인 추가

---

packages/frontend/src/pages/GamePage/GamePage.component.tsx

closes #101 
- GamePage 사용하지 않는 변수 삭제
- non-null 단언 연산자 제거 및 널 병합 연산자 사용
- 시간 제한으로 인한 라운드 종료 시 문구 추가

[FIX] 시간 제한으로 인한 라운드 종료 시 문구 추가

---

.github/workflows/CI.yml
packages/backend/src/app.ts

closes  #104 
- 불 필요한 CI 개선
- 파일 변경이 있는 경우 install, lint, test, build 하도록 변경
- [참고 액션](https://github.com/marketplace/actions/changed-files )

[FEAT] 변경된 부분에 한하여 CI 하기

---

packages/frontend/src/hooks/useCatchMind.tsx

closes #113 
- gamePlayerList가 업데이트 될때마다 소켓 이벤트가 중복으로 등록되는 현상 수정

[FIX] 다음 라운드 버튼 클릭 시 플레이어 리스트 색상이 바뀌지 않는 현상

---

packages/backend/src/app.ts
packages/backend/src/domains/garticphone/entity/garticphone.service.ts
packages/backend/src/domains/garticphone/entity/garticphone.ts
packages/backend/src/domains/garticphone/inbound/garticphone.controller.ts
packages/backend/src/domains/garticphone/inbound/garticphone.port.ts
packages/backend/src/domains/garticphone/outbound/garitcphone.repository.port.ts
packages/backend/src/domains/garticphone/outbound/garticphone.repository.ts
packages/backend/src/domains/garticphone/outbound/garticphoneEvent.adapter.ts
packages/backend/src/domains/garticphone/outbound/garticphoneEvent.port.ts
packages/backend/src/domains/room/outbound/room.api.adapter.ts

#88
- 백엔드 갈틱폰 게임 시작 및 제시어 입력 부분 구현

[FEAT] 갈틱폰 제시어 입력 기능

---

packages/frontend/src/pages/RoomPage/RoomPage.component.tsx

- 중복 import 제거
- 빠진 type import 추가

[FIX] 방 페이지 오류 수정

---

packages/frontend/src/pages/LandingPage/LandingPage.component.tsx

closes #129
- room id 전달 안되는 오류 수정

[FIX] room id 전달 안되는 오류 수정

---

packages/frontend/src/components/PlayerList/PlayerListItem/PlayerListItem.component.tsx
packages/frontend/src/components/PlayerList/PlayerListItem/PlayerListItem.styles.tsx
packages/frontend/src/hooks/useAudioCommunication.tsx
packages/frontend/src/pages/LandingPage/LandingPage.component.tsx
packages/frontend/src/pages/RoomPage/RoomPage.component.tsx
packages/frontend/src/types/game.ts
packages/frontend/src/utils/audioStreamMap.ts

closes #91
- AudioStreamManager에 음향 분석을 위한 코드 구현
- 오디오 감지 이벤트 리스너 등록 구현
- 음성 감지 UI 구현
- 본인의 음성이 재생되지 않도록 함

[FEAT] 음성 입력 UI 피드백

---

packages/backend/src/domains/garticphone/entity/garticphone.service.ts
packages/backend/src/domains/garticphone/entity/garticphone.ts
packages/backend/src/domains/garticphone/inbound/garticphone.controller.ts
packages/backend/src/domains/garticphone/outbound/garticphoneEvent.adapter.ts
packages/backend/src/domains/garticphone/outbound/garticphoneEvent.port.ts
packages/backend/src/utils/socketEmitter.ts

#90 
- 제시어 입력 및 그림 그리기 완료시 다음 라운드 소켓이벤트 전송
- 타임아웃 설정

[FEAT] 그리기 라운드 구현

---

packages/backend/src/domains/garticphone/entity/garticphone.service.ts
packages/backend/src/domains/garticphone/entity/garticphone.ts
packages/backend/src/domains/garticphone/inbound/garticphone.controller.ts
packages/backend/src/domains/garticphone/inbound/garticphone.port.ts
packages/backend/src/domains/garticphone/outbound/garticphoneEvent.adapter.ts
packages/backend/src/domains/garticphone/outbound/garticphoneEvent.port.ts
packages/backend/src/domains/garticphone/outbound/garticphoneToRoom.adapter.ts
packages/backend/src/domains/garticphone/outbound/garticphoneToRoom.port.ts
packages/backend/src/domains/room/entity/room.entity.ts
packages/backend/src/domains/room/entity/room.service.ts
packages/backend/src/domains/room/inbound/room.controller.ts
packages/backend/src/domains/room/inbound/room.port.ts
packages/backend/src/domains/room/outbound/room.api.adapter.ts
packages/backend/src/domains/room/outbound/room.port.ts
packages/backend/src/domains/room/outbound/room.repository.ts

#97 
- 게임 중간에 나가는 소켓 이벤트 연결
- 방에서 게임모드 선택 리팩토링

[FEAT] 게임에서 중간에 나가는 이벤트 구현

---

packages/frontend/src/components/Album/Album.component.tsx
packages/frontend/src/components/Album/Album.styles.tsx
packages/frontend/src/components/Album/AlbumBubble.component.tsx
packages/frontend/src/components/Chat/Chat.component.tsx
packages/frontend/src/components/Chat/Chat.styles.tsx
packages/frontend/src/components/Chat/ChatBubble.component.tsx
packages/frontend/src/components/Gartic/Gartic.component.tsx
packages/frontend/src/components/Gartic/Gartic.styles.tsx
packages/frontend/src/hooks/useGartic.tsx
packages/frontend/src/types/game.ts

closes #95 #96
- 앨범 컴포넌트 구현
- 게임 종료 화면 구현

[FEAT] 갈틱폰 모드 게임 결과 페이지

---

packages/frontend/src/components/CatchMind/CatchMind.component.tsx
packages/frontend/src/components/Gartic/Gartic.component.tsx
packages/frontend/src/components/MoonTimer/MoonTimer.component.tsx
packages/frontend/src/components/NicknameInput/NicknameInput.component.tsx
packages/frontend/src/pages/LandingPage/LandingPage.component.tsx
packages/frontend/src/store/nickname.ts

closes #162 
- 타이머 초기화 오류 수정
- 닉네임 및 제시어 입력 리렌더링 개선

[FIX] 타이머 초기화 오류 수정

---

packages/backend/src/domains/catchMind/outbound/CatchMindEvent.Adapter.ts
packages/backend/src/domains/garticphone/entity/garticphone.service.ts
packages/backend/src/domains/garticphone/outbound/garticphoneToRoom.adapter.ts
packages/frontend/src/components/CatchMind/CatchMind.component.tsx
packages/frontend/src/pages/GamePage/GamePage.component.tsx

closes #163 
- 캐치마인드 퇴장 이벤트 추가

[FIX] 캐치마인드 퇴장 이벤트 추가로 갈틱폰 오류 수정

---

packages/backend/src/domains/catchMind/entity/catchMind.service.ts
packages/backend/src/domains/catchMind/entity/catchMind.ts
packages/backend/src/domains/catchMind/inbound/CatchMindInput.port.ts
packages/backend/src/domains/catchMind/inbound/catchMindAPI.controller.ts
packages/backend/src/domains/catchMind/inbound/catchMindInput.controller.ts
packages/backend/src/domains/catchMind/outbound/CatchMindEvent.Adapter.ts
packages/backend/src/domains/catchMind/outbound/catchMind.repository.port.ts
packages/backend/src/domains/catchMind/outbound/catchMind.repository.ts
packages/backend/src/domains/catchMind/outbound/timer.repository.port.ts
packages/backend/src/domains/catchMind/outbound/timer.repository.ts
packages/backend/src/domains/garticphone/entity/garticphone.service.ts
packages/backend/src/domains/garticphone/entity/garticphone.ts
packages/backend/src/domains/garticphone/inbound/garticphone.controller.ts
packages/backend/src/domains/garticphone/outbound/garitcphone.repository.port.ts
packages/backend/src/domains/garticphone/outbound/garticphone.repository.ts
packages/backend/src/domains/garticphone/outbound/timer.repository.port.ts
packages/backend/src/domains/garticphone/outbound/timer.repository.ts
packages/backend/src/domains/player/entity/player.service.ts
packages/backend/src/domains/player/inbound/player.controller.ts
packages/backend/src/domains/room/entity/room.service.ts
packages/backend/src/domains/room/inbound/room.controller.ts
packages/backend/src/domains/room/outbound/room.repository.ts

#145
- 타이머 로직 수정
- 갈틱폰, 캐치마인드 엔티티 저장 및 복원 구현
- 게임 중 방에서 나가는 로직 수정

[FEAT] 게임로직 redis 연결 및 방에서 나가는 로직 수정

---

package-lock.json
packages/frontend/package.json
packages/frontend/src/pages/LandingPage/LandingPage.component.tsx
packages/frontend/src/pages/RoomPage/RoomPage.component.tsx

closes #144 
- `react-hot-toast` 라이브러리 설치
- 초대 링크 복사 시 토스트 메시지 출력
- 랜딩 페이지 에러 메시지 출력
- 랜딩 페이지 초대 링크인 경우 메시지 출력

[FEAT] 초대 기능 UX 개선

---

packages/frontend/src/pages/RoomPage/RoomPage.styles.tsx

closes #196
- 방 페이지 배경 1개만 보이도록 수정

[FIX] 방 페이지 배경 수정

---

packages/frontend/src/components/CatchMind/CatchMind.component.tsx
packages/frontend/src/pages/LandingPage/LandingPage.component.tsx
packages/frontend/src/pages/RoomPage/RoomPage.component.tsx

[FIX] 로고 수축 수정

---

packages/frontend/src/App.tsx
packages/frontend/src/pages/LandingPage/LandingPage.component.tsx
packages/frontend/src/pages/LandingPage/LandingPage.styles.tsx
packages/frontend/src/pages/RoomPage/RoomPage.component.tsx

closes #194
- 모든 플레이어가 방에 돌아오지 않았을 때 게임 시작 시 토스트 메시지 출력
- 축소 비율 FHD에 맞게 수정
- 랜딩 페이지 반응형 적용

[FEAT] 모든 플레이어가 방에 돌아오지 않았을 때 토스트 메시지 출력

---

packages/frontend/src/hooks/useAudioCommunication.tsx
packages/frontend/src/hooks/useDataConnectionWithPeers.tsx

closes #204 
- 통신 관련 hook null 처리

[FIX] 방 및 게임 페이지에서 새로고침 시 통신 관련 hook 오류

---

packages/frontend/src/utils/audioStreamManager.ts

closes #206 
- 상대방 음소거 버튼을 처음 클릭할 때 아이콘이 바뀌지 않는 오류 수정

[FIX] 음소거 아이콘 오류 수정

---

packages/frontend/src/components/Game/Gartic/Gartic.component.tsx
packages/frontend/src/components/PlayerList/PlayerListItem/PlayerListItem.component.tsx

closes #208
- 갈틱폰 모드 제시어 입력 단계에서 타이머 동작하지 않는 오류 수정

[FIX] 갈틱폰 모드 제시어 입력 단계 타이머 동작

---

packages/backend/src/config/redis.ts
packages/frontend/src/components/Canvas/Canvas.component.tsx
packages/frontend/src/components/Palette/Palette.component.tsx
packages/frontend/src/components/Thickness/Thickness.component.tsx
packages/frontend/src/components/ToolBox/ToolBox.component.tsx
packages/frontend/src/components/Transparency/Transparency.component.tsx
packages/frontend/src/hooks/useCatchMind.tsx
packages/frontend/src/hooks/useDataConnectionWithPeers.tsx
packages/frontend/src/store/thickness.ts
packages/frontend/src/store/tool.ts
packages/frontend/src/store/transparency.ts

- 캔버스 채우기 버그 수정
- 불필요한 console.log 제거 
- redis 연결 url 변경
- 캔버스 마운트시 기존 설정 초기화

[FIX] 배포후 발견된 버그 수정 및 개선점 적용 

---

packages/backend/src/domains/catchMind/entity/catchMind.ts
packages/backend/src/domains/catchMind/useCases/catchMind.service.ts

Reverts boostcampwm-2022/web15-Teleparty#235

Revert "[FEAT] 캐치마인드 목표 점수와 라운드를 사람 수에 맞게 조정"

---

packages/backend/src/domains/garticphone/controllers/garticphone.controller.ts
packages/backend/src/domains/garticphone/entity/garticphone.ts
packages/backend/src/domains/garticphone/useCases/garticphone.service.ts
packages/backend/src/domains/garticphone/useCases/garticphoneController.port.ts
packages/backend/src/domains/room/controllers/searchRoom.api.port.ts
packages/backend/src/domains/room/entity/room.entity.ts
packages/backend/src/domains/room/presenters/room.api.adapter.ts
packages/backend/src/domains/room/presenters/room.port.ts
packages/backend/src/domains/room/useCases/room.service.ts

closes #225
- 룸에서 게임모드 시간을 따로 저장
- 갈틱폰 라운드 시간 로직 변경

[FEAT] 갈틱폰 라운드 시간 변경

---

packages/backend/src/domains/catchMind/entity/catchMind.ts
packages/backend/src/domains/catchMind/useCases/catchMind.service.ts
packages/backend/src/domains/room/useCases/room.service.ts

closes #233 
- 게임 종료 로직 수정
- 룸에서 2명이 있을 때 한명이 나가면 방이 터지는 버그 수정

[FEAT] 캐치마인드 1명 남았을 때 게임 종료

---

package-lock.json
packages/frontend/package.json
packages/frontend/src/components/Album/Album.component.tsx
packages/frontend/src/components/Game/CatchMind/CatchMind.component.tsx
packages/frontend/src/components/Game/Game.components.tsx
packages/frontend/src/hooks/useCreateGIF.ts
packages/frontend/src/hooks/useCreateImage.ts
packages/frontend/src/hooks/useUsername.ts
packages/frontend/src/types/gifshot/index.d.ts
packages/frontend/src/utils/date.ts
packages/frontend/tsconfig.json

closes #222 
- 그림/제시어 이미지 다운로드 기능 구현
- 결과 앨범 gif 다운로드 기능 구현

[FEAT] 게임 결과물 저장하기
